"""Initial schema for the payments application."""

# Generated by Django 4.2.24 on 2025-09-17 17:58

# pylint: disable=invalid-name,missing-class-docstring,line-too-long

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0001_initial'),
        ('users', '0002_delete_collaborator_delete_organisation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='EUR', max_length=10)),
                ('max_athletes', models.PositiveIntegerField(default=0)),
                ('max_collaborators', models.PositiveIntegerField(default=0)),
                ('features', models.JSONField(blank=True, default=dict)),
                ('stripe_product_id', models.CharField(blank=True, max_length=255)),
                ('stripe_price_id', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={'abstract': False},
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('active', 'Active'),
                            ('past_due', 'Past Due'),
                            ('canceled', 'Canceled'),
                            ('incomplete', 'Incomplete'),
                        ],
                        default='active',
                        max_length=20,
                    ),
                ),
                ('start_at', models.DateTimeField()),
                ('current_period_end', models.DateTimeField()),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=255)),
                (
                    'agent',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='subscriptions',
                        to='users.agentprofile',
                    ),
                ),
                (
                    'organisation',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='subscriptions',
                        to='organisations.organisation',
                    ),
                ),
                (
                    'plan',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='subscriptions',
                        to='payments.subscriptionplan',
                    ),
                ),
            ],
            options={
                'indexes': [
                    models.Index(
                        fields=['organisation'],
                        name='payments_su_organis_bb7136_idx',
                    ),
                    models.Index(
                        fields=['agent'],
                        name='payments_su_agent_i_e0d720_idx',
                    ),
                ],
            },
        ),
    ]
