"""Rename legacy subscription indexes and reapply constraint."""

# Generated by Django 4.2.24 on 2025-09-17 18:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="subscription",
            new_name="subscription_organisation_idx",
            old_name="payments_su_organis_bb7136_idx",
        ),
        migrations.RenameIndex(
            model_name="subscription",
            new_name="subscription_agent_idx",
            old_name="payments_su_agent_i_e0d720_idx",
        ),
        migrations.AddConstraint(
            model_name="subscription",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("agent__isnull", True), ("organisation__isnull", False)),
                    models.Q(("agent__isnull", False), ("organisation__isnull", True)),
                    _connector="OR",
                ),
                name="subscription_scope_xor",
            ),
        ),
    ]
