"""Seed default subscription plans for payments."""

# Generated by Django 4.2.24 on 2025-09-17 18:30

from decimal import Decimal

from django.db import migrations


def seed_subscription_plans(apps, schema_editor):
    """Populate the subscription plan table with baseline plans."""

    del schema_editor

    subscription_plan_model = apps.get_model("payments", "SubscriptionPlan")

    plans = [
        {
            "code": "agent-free",
            "name": "Agent Free",
            "price": Decimal("0.00"),
            "currency": "EUR",
            "max_athletes": 1,
            "max_collaborators": 0,
            "features": {
                "tier": "agent",
                "messaging_tier": "none",
                "max_messages_per_month": 0,
                "search_visibility_pct": 50,
                "stats_tier": "basic",
                "comparative_stats": False,
                "agent_subscription_management": True,
                "contract_tools": "disabled",
                "notification_center": False,
            },
        },
        {
            "code": "agent-pro",
            "name": "Agent Pro",
            "price": Decimal("50.00"),
            "currency": "EUR",
            "max_athletes": 5,
            "max_collaborators": 0,
            "features": {
                "tier": "agent",
                "messaging_tier": "limited",
                "max_messages_per_month": 200,
                "search_visibility_pct": 100,
                "stats_tier": "advanced",
                "comparative_stats": False,
                "agent_subscription_management": True,
                "contract_tools": "enabled",
                "notification_center": True,
            },
        },
        {
            "code": "agent-agency",
            "name": "Agent Agency",
            "price": Decimal("149.99"),
            "currency": "EUR",
            "max_athletes": 20,
            "max_collaborators": 0,
            "features": {
                "tier": "agent",
                "messaging_tier": "pro_plus",
                "max_messages_per_month": None,
                "search_visibility_pct": 130,
                "stats_tier": "premium",
                "comparative_stats": True,
                "agent_subscription_management": True,
                "contract_tools": "enabled",
                "notification_center": True,
            },
        },
        {
            "code": "org-starter",
            "name": "Organisation Starter",
            "price": Decimal("149.00"),
            "currency": "EUR",
            "max_athletes": 0,
            "max_collaborators": 3,
            "features": {
                "tier": "organisation",
                "max_follows": 10,
                "collaborator_invites": True,
                "organisation_subscription_management": True,
                "athlete_stats_scope": "engagement",
                "data_access": ["follows", "engagement"],
                "contract_tools": "disabled",
                "notification_center": True,
            },
        },
        {
            "code": "org-pro",
            "name": "Organisation Pro",
            "price": Decimal("399.00"),
            "currency": "EUR",
            "max_athletes": 0,
            "max_collaborators": 10,
            "features": {
                "tier": "organisation",
                "max_follows": 10,
                "collaborator_invites": True,
                "organisation_subscription_management": True,
                "athlete_stats_scope": "all",
                "data_access": ["follows", "engagement", "demographic"],
                "contract_tools": "enabled",
                "notification_center": True,
            },
        },
        {
            "code": "org-enterprise",
            "name": "Organisation Enterprise",
            "price": Decimal("999.00"),
            "currency": "EUR",
            "max_athletes": 0,
            "max_collaborators": 0,  # 0 == unlimited
            "features": {
                "tier": "organisation",
                "max_follows": 10,
                "collaborator_invites": True,
                "organisation_subscription_management": True,
                "athlete_stats_scope": "all",
                "data_access": ["follows", "engagement", "demographic", "api"],
                "contract_tools": "enabled",
                "notification_center": True,
            },
        },
    ]

    for plan_data in plans:
        defaults = plan_data.copy()
        defaults.pop("code")
        subscription_plan_model.objects.update_or_create(
            code=plan_data["code"],
            defaults=defaults,
        )


def unseed_subscription_plans(apps, schema_editor):
    """Remove seeded subscription plans."""

    del schema_editor

    subscription_plan_model = apps.get_model("payments", "SubscriptionPlan")
    subscription_plan_model.objects.filter(
        code__in=[
            "agent-free",
            "agent-pro",
            "agent-agency",
            "org-starter",
            "org-pro",
            "org-enterprise",
        ],
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        (
            "payments",
            "0002_rename_payments_su_organis_bb7136_idx_subscription_organisation_idx_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(seed_subscription_plans, unseed_subscription_plans),
    ]
