# Generated by Django 4.2.24 on 2026-06-23 01:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("contracts", "0011_marketplace_fee_models"),
        ("athletes", "0012_sport_business_and_entourage"),
        ("payments", "0005_alter_subscription_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="AthletePaymentAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("stripe_account_id", models.CharField(max_length=255, unique=True)),
                ("is_onboarded", models.BooleanField(default=False)),
                ("charges_enabled", models.BooleanField(default=False)),
                ("payouts_enabled", models.BooleanField(default=False)),
                (
                    "athlete",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_account",
                        to="athletes.athlete",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PlatformFee",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fee_type",
                    models.CharField(
                        choices=[
                            ("cash_commission", "Cash commission (10 %)"),
                            (
                                "material_fixed_fee",
                                "Fixed fee – material contract (€49)",
                            ),
                        ],
                        max_length=32,
                    ),
                ),
                ("amount_due", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending payment"),
                            ("paid", "Paid"),
                            ("disputed", "Disputed"),
                            ("waived", "Waived by staff"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "stripe_payment_intent_id",
                    models.CharField(blank=True, max_length=255),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "contract",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="platform_fee",
                        to="contracts.contract",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["status"], name="platform_fee_status_idx")
                ],
            },
        ),
    ]
