# Generated by Django 4.2.24 on 2025-09-17 17:35


from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Collaborator",
        ),
        migrations.DeleteModel(
            name="Organisation",
        ),
    ]
