# Generated by Django 4.2.24 on 2025-09-17 18:29


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_delete_collaborator_delete_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('AGENT', 'Agent'), ('ORGANISATION', 'Organisation')], default='AGENT', max_length=20, verbose_name='account type'),
        ),
    ]
