# Generated by Django 4.2.24 on 2025-09-25 21:20

from django.db import migrations, models


def copy_self_represented_flag(apps, schema_editor):
    AgentProfile = apps.get_model("users", "AgentProfile")
    Athlete = apps.get_model("athletes", "Athlete")
    agent_ids = (
        Athlete.objects.filter(is_self_represented=True)
        .values_list("agent_id", flat=True)
        .distinct()
    )
    if agent_ids:
        AgentProfile.objects.filter(id__in=agent_ids).update(is_self_represented=True)


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_user_phone_country_code_alter_user_phone_number_and_more"),
        ("athletes", "0003_sport_emoji"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentprofile",
            name="is_self_represented",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(copy_self_represented_flag, migrations.RunPython.noop),
    ]
