# Generated by Django 4.2.24 on 2025-09-29 00:42
# Generated by Django 4.2.24 on 2025-09-29 00:42

import uuid

from django.db import migrations, models
from django.utils.text import slugify


def populate_user_slugs(apps, schema_editor):
    """Populate slugs for existing user records."""

    User = apps.get_model("users", "User")
    for user in User.objects.filter(slug__isnull=True):
        base_parts = [part for part in [user.first_name, user.last_name] if part]
        base_slug = slugify(" ".join(base_parts))
        if not base_slug and user.email:
            base_slug = slugify(user.email.split("@")[0])
        if not base_slug:
            base_slug = uuid.uuid4().hex[:8]

        slug_candidate = base_slug
        counter = 1
        while (
            User.objects.filter(slug=slug_candidate)
            .exclude(pk=user.pk)
            .exists()
        ):
            counter += 1
            slug_candidate = f"{base_slug}-{counter}"

        user.slug = slug_candidate
        user.save(update_fields=["slug"])


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_agentprofile_is_self_represented"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.RunPython(populate_user_slugs, migrations.RunPython.noop),
    ]
