# Generated by Django 4.2.24 on 2026-06-22 23:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_alter_user_country_alter_user_language"),
    ]

    operations = [
        migrations.CreateModel(
            name="RepresentativeProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_kyc_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Representative has passed identity verification.",
                    ),
                ),
                (
                    "license_number",
                    models.CharField(
                        blank=True,
                        help_text="Federation license number — populated only for certified sports agents.",
                        max_length=100,
                    ),
                ),
                (
                    "licensing_federation",
                    models.CharField(
                        blank=True,
                        help_text="Federation that issued the agent license (e.g., FFF, FFBB).",
                        max_length=255,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="representative_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
