"""Shared pytest fixtures for the Sponsors Club test suite."""

from __future__ import annotations

import os
from typing import Generator

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'core.settings')

# pylint: disable=wrong-import-position,no-member

import django

django.setup()

import pytest
from django.contrib.auth import get_user_model
from django.core.management import call_command
from django.utils import timezone
from rest_framework.test import APIClient

from organisations.models import Collaborator, Organisation
from payments.models import Subscription, SubscriptionPlan
from users.models import AgentProfile


@pytest.fixture(autouse=True)
def reset_db(django_db_blocker) -> Generator[None, None, None]:
    """Flush the database after each test to guarantee isolation."""

    yield
    with django_db_blocker.unblock():
        call_command('flush', verbosity=0, interactive=False)


@pytest.fixture
def api_client() -> APIClient:
    """Return a DRF API client for convenience in tests."""

    return APIClient()


@pytest.fixture(name='user_model')
def fixture_user_model():
    """Expose the Django user model to dependent fixtures."""

    return get_user_model()


@pytest.fixture(name='agent_user')
def fixture_agent_user(user_model):
    """Create and return a test agent user with profile."""

    user = user_model.objects.create_user(
        email='agent@test.com',
        password='pass1234',
        first_name='Agent',
        last_name='User',
        account_type=user_model.AccountType.AGENT,
    )
    AgentProfile.objects.create(user=user, display_name='Agent One')
    return user


@pytest.fixture
def owner_user(organisations_setup):
    """Return the organisation owner generated by organisations_setup."""

    return organisations_setup['owner']


@pytest.fixture(name='organisations_setup')
def fixture_organisations_setup(user_model):
    """Create an organisation, collaborator owner, and active subscription."""

    owner = user_model.objects.create_user(
        email='owner@test.com',
        password='pass1234',
        first_name='Owner',
        last_name='User',
        account_type=user_model.AccountType.COLLABORATOR,
    )
    organisation = Organisation.objects.create(
        owner=owner,
        name='Test Org',
        sector='Tech',
        size=Organisation.Size.MEDIUM,
        budget_min=1000,
        budget_max=2000,
        country='FR',
    )
    collaborator = Collaborator.objects.create(
        user=owner,
        organisation=organisation,
        role=Collaborator.Role.OWNER,
        job_title='Owner',
    )

    plan = SubscriptionPlan.objects.get(code='org-enterprise')
    subscription = Subscription.objects.create(
        organisation=organisation,
        plan=plan,
        status=Subscription.Status.ACTIVE,
        start_at=timezone.now(),
        current_period_end=timezone.now(),
    )
    return {
        'owner': owner,
        'organisation': organisation,
        'collaborator': collaborator,
        'subscription': subscription,
    }


@pytest.fixture(name='agent_subscription')
def fixture_agent_subscription(agent_user):
    """Create an agent subscription tied to the agent_user fixture."""

    plan = SubscriptionPlan.objects.get(code='agent-agency')
    subscription = Subscription.objects.create(
        agent=agent_user.agent_profile,
        plan=plan,
        status=Subscription.Status.ACTIVE,
        start_at=timezone.now(),
        current_period_end=timezone.now(),
    )
    return subscription


@pytest.fixture
def organisation_subscription(organisations_setup):
    """Return the active organisation subscription fixture."""

    return organisations_setup['subscription']
