# pylint: skip-file
# Generated by Django 4.2.24 on 2025-09-17 18:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("athletes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AthleteStat",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "metric",
                    models.CharField(
                        choices=[
                            ("followers", "Followers"),
                            ("engagement", "Engagement"),
                            ("rank", "Rank"),
                            ("custom", "Custom"),
                        ],
                        max_length=32,
                    ),
                ),
                ("value", models.DecimalField(decimal_places=2, max_digits=12)),
                ("date", models.DateField()),
                ("extra", models.JSONField(blank=True, default=dict)),
                (
                    "athlete",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to="athletes.athlete",
                    ),
                ),
            ],
            options={
                "ordering": ("athlete", "metric", "-date"),
                "indexes": [
                    models.Index(
                        fields=["metric", "date"], name="analytics_a_metric_38ed28_idx"
                    )
                ],
                "unique_together": {("athlete", "metric", "date")},
            },
        ),
    ]
