# Generated by Django 4.2.24 on 2025-09-20 04:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("athletes", "0001_initial"),
        (
            "analytics",
            "0002_rename_analytics_a_metric_38ed28_idx_athstat_metric_date_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="AthleteSocialAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("username", models.CharField(max_length=255)),
                ("external_id", models.CharField(max_length=255, unique=True)),
                ("access_token", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "athlete",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_accounts",
                        to="athletes.athlete",
                    ),
                ),
            ],
            options={
                "ordering": ("athlete", "platform__name"),
            },
        ),
        migrations.CreateModel(
            name="DailyStats",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                ("followers", models.PositiveIntegerField()),
                ("following", models.PositiveIntegerField(blank=True, null=True)),
                ("posts_count", models.PositiveIntegerField()),
                ("likes", models.PositiveIntegerField()),
                ("comments", models.PositiveIntegerField()),
                ("shares", models.PositiveIntegerField(blank=True, null=True)),
                ("views", models.PositiveIntegerField(blank=True, null=True)),
                ("watch_time", models.FloatField(blank=True, null=True)),
                ("engagement_rate", models.FloatField(editable=False)),
                ("top_post", models.JSONField(blank=True, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_stats",
                        to="analytics.athletesocialaccount",
                    ),
                ),
            ],
            options={
                "ordering": ("account", "-date"),
            },
        ),
        migrations.CreateModel(
            name="SocialPlatform",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("tiktok", "TikTok"),
                            ("instagram", "Instagram"),
                            ("facebook", "Facebook"),
                            ("youtube", "YouTube"),
                        ],
                        max_length=32,
                        unique=True,
                    ),
                ),
                ("base_url", models.URLField(blank=True, null=True)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.DeleteModel(
            name="AthleteStat",
        ),
        migrations.AddField(
            model_name="athletesocialaccount",
            name="platform",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accounts",
                to="analytics.socialplatform",
            ),
        ),
        migrations.AddIndex(
            model_name="dailystats",
            index=models.Index(
                fields=["account", "date"], name="dailystats_account_date_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="dailystats",
            constraint=models.UniqueConstraint(
                fields=("account", "date"), name="unique_stats_per_account_day"
            ),
        ),
        migrations.AddConstraint(
            model_name="athletesocialaccount",
            constraint=models.UniqueConstraint(
                fields=("athlete", "platform"), name="unique_account_per_platform"
            ),
        ),
    ]
