"""Initial database schema for the follows application."""

# Generated by Django 4.2.24 on 2025-09-17 17:49

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("athletes", "0001_initial"),
        ("organisations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Follow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("notify_news", models.BooleanField(default=True)),
                ("notify_stats", models.BooleanField(default=True)),
                ("notify_contracts", models.BooleanField(default=True)),
                (
                    "athlete",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="follows",
                        to="athletes.athlete",
                    ),
                ),
                (
                    "collaborator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="follows",
                        to="organisations.collaborator",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["athlete", "collaborator"],
                        name="follows_fol_athlete_490c7f_idx",
                    )
                ],
                "unique_together": {("collaborator", "athlete")},
            },
        ),
    ]
