# pylint: skip-file
# pylint: disable=duplicate-code
# Generated by Django 4.2.24 on 2025-09-17 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organisations', '0001_initial'),
        ('athletes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClauseTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identifier', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('obligation', 'Obligation'), ('condition', 'Condition'), ('paiement', 'Paiement'), ('duree', 'Durée'), ('legal', 'Légal')], max_length=20)),
                ('content', models.TextField(help_text='Content supporting placeholder tokens like [key].')),
                ('placeholders', models.JSONField(blank=True, default=list)),
                ('mandatory', models.BooleanField(default=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('identifier', 'version'),
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('AGREEMENT', 'Agreement'), ('VERIFICATION', 'Verification'), ('ACTIVE', 'Active'), ('TERMINATED', 'Terminated')], default='DRAFT', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='EUR', max_length=10)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='athletes.athlete')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_contracts', to='organisations.collaborator')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='organisations.organisation')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ContractVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_number', models.PositiveIntegerField()),
                ('snapshot', models.JSONField(default=dict)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='contracts.contract')),
            ],
            options={
                'ordering': ('contract', '-version_number'),
                'unique_together': {('contract', 'version_number')},
            },
        ),
        migrations.CreateModel(
            name='ContractStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_status', models.CharField(blank=True, choices=[('DRAFT', 'Draft'), ('AGREEMENT', 'Agreement'), ('VERIFICATION', 'Verification'), ('ACTIVE', 'Active'), ('TERMINATED', 'Terminated')], max_length=20, null=True)),
                ('to_status', models.CharField(choices=[('DRAFT', 'Draft'), ('AGREEMENT', 'Agreement'), ('VERIFICATION', 'Verification'), ('ACTIVE', 'Active'), ('TERMINATED', 'Terminated')], max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_status_changes', to=settings.AUTH_USER_MODEL)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='contracts.contract')),
            ],
            options={
                'ordering': ('-changed_at',),
                'indexes': [models.Index(fields=['contract', 'changed_at'], name='contracts_c_contrac_3469d5_idx')],
            },
        ),
        migrations.CreateModel(
            name='ContractClause',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('values', models.JSONField(blank=True, default=dict)),
                ('order_index', models.PositiveIntegerField()),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clauses', to='contracts.contract')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contract_clauses', to='contracts.clausetemplate')),
            ],
            options={
                'ordering': ('contract', 'order_index'),
                'unique_together': {('contract', 'template', 'order_index')},
            },
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['organisation', 'status'], name='contracts_c_organis_09059c_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['athlete'], name='contracts_c_athlete_5b086e_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['start_date'], name='contracts_c_start_d_4c01aa_idx'),
        ),
    ]
