# Generated by Django 4.2.24 on 2025-09-20 17:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organisations", "0005_organisation_owner"),
        ("users", "0005_remove_user_id_remove_user_username_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClauseTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ADMINISTRATIVE", "Administratives"),
                            ("OBLIGATIONS", "Obligations"),
                            ("FINANCE", "Finance"),
                            ("IP", "IP"),
                            ("ETHICS", "Ethics"),
                            ("CONFIDENTIALITY", "Confidentiality"),
                            ("TERMINATION", "Résiliation"),
                        ],
                        max_length=32,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("placeholders", models.JSONField(blank=True, default=list)),
                ("is_mandatory", models.BooleanField(default=False)),
                ("version", models.PositiveIntegerField(default=1)),
            ],
            options={
                "ordering": ("category", "title", "version"),
                "unique_together": {("title", "version")},
            },
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("negotiation", "Negotiation"),
                            ("agreement", "Agreement"),
                            ("active", "Active"),
                            ("terminated", "Terminated"),
                        ],
                        default="draft",
                        max_length=32,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("effective_date", models.DateField(blank=True, null=True)),
                ("expiration_date", models.DateField(blank=True, null=True)),
                ("organisation_name", models.CharField(blank=True, max_length=255)),
                (
                    "organisation_legal_name",
                    models.CharField(blank=True, max_length=255),
                ),
                ("organisation_type", models.CharField(blank=True, max_length=100)),
                (
                    "organisation_registration_number",
                    models.CharField(blank=True, max_length=100),
                ),
                ("organisation_tax_id", models.CharField(blank=True, max_length=100)),
                ("organisation_address", models.TextField(blank=True)),
                ("organisation_country", models.CharField(blank=True, max_length=100)),
                (
                    "organisation_representative",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "organisation_representative_title",
                    models.CharField(blank=True, max_length=255),
                ),
                ("athlete_name", models.CharField(blank=True, max_length=255)),
                ("athlete_birthdate", models.DateField(blank=True, null=True)),
                ("athlete_birthplace", models.CharField(blank=True, max_length=255)),
                ("athlete_address", models.TextField(blank=True)),
                ("athlete_nationality", models.CharField(blank=True, max_length=100)),
                ("athlete_sport", models.CharField(blank=True, max_length=100)),
                ("athlete_team", models.CharField(blank=True, max_length=255)),
                (
                    "athlete_license_number",
                    models.CharField(blank=True, max_length=100),
                ),
                ("agent_name", models.CharField(blank=True, max_length=255)),
                ("agent_address", models.TextField(blank=True)),
                ("agent_registration_id", models.CharField(blank=True, max_length=100)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "contract_duration_months",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("renewal_terms", models.TextField(blank=True)),
                ("termination_date", models.DateField(blank=True, null=True)),
                (
                    "notice_period_days",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("event_calendar", models.JSONField(blank=True, default=list)),
                (
                    "number_of_events",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("event_types_required", models.JSONField(blank=True, default=list)),
                ("posts_per_month", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "stories_per_month",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("video_mentions", models.PositiveIntegerField(blank=True, null=True)),
                ("hashtags_required", models.JSONField(blank=True, default=list)),
                ("equipment_usage", models.TextField(blank=True)),
                ("sector_exclusivity", models.CharField(blank=True, max_length=255)),
                ("competitions_mandatory", models.JSONField(blank=True, default=list)),
                ("performance_goals", models.TextField(blank=True)),
                ("training_commitment", models.CharField(blank=True, max_length=255)),
                (
                    "injury_notification_delay",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("equipment_provided", models.TextField(blank=True)),
                ("support_logistics", models.TextField(blank=True)),
                ("insurance_details", models.TextField(blank=True)),
                ("media_exposure", models.TextField(blank=True)),
                ("promotion_channels", models.JSONField(blank=True, default=list)),
                ("brand_guidelines", models.TextField(blank=True)),
                (
                    "total_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("currency", models.CharField(default="EUR", max_length=10)),
                ("payment_schedule", models.TextField(blank=True)),
                ("payment_method", models.CharField(blank=True, max_length=100)),
                (
                    "bonus_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("bonus_conditions", models.TextField(blank=True)),
                (
                    "royalty_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("royalty_base", models.CharField(blank=True, max_length=255)),
                (
                    "penalty_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("image_rights_scope", models.TextField(blank=True)),
                ("duration_years", models.PositiveIntegerField(blank=True, null=True)),
                ("territory", models.CharField(blank=True, max_length=255)),
                ("media_types_allowed", models.JSONField(blank=True, default=list)),
                ("exclusivity_level", models.CharField(blank=True, max_length=100)),
                ("license_transfer_terms", models.TextField(blank=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contracts",
                        to="users.agentprofile",
                    ),
                ),
                (
                    "initiated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="initiated_contracts",
                        to="organisations.collaborator",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contracts",
                        to="organisations.organisation",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="ContractClause",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("position", models.PositiveIntegerField(default=0)),
                ("is_mandatory", models.BooleanField(default=False)),
                ("is_modified", models.BooleanField(default=False)),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clauses",
                        to="contracts.contract",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contract_clauses",
                        to="contracts.clausetemplate",
                    ),
                ),
            ],
            options={
                "ordering": ("position", "created_at"),
            },
        ),
        migrations.CreateModel(
            name="ContractRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("comment", models.TextField(blank=True)),
                ("accepted", models.BooleanField(default=False)),
                (
                    "clauses_changed",
                    models.ManyToManyField(
                        blank=True,
                        related_name="revisions",
                        to="contracts.contractclause",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="contracts.contract",
                    ),
                ),
                (
                    "proposed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proposed_revisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="ContractFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pdf",
                    models.FileField(
                        blank=True, null=True, upload_to="contract_exports/"
                    ),
                ),
                (
                    "contract",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="file",
                        to="contracts.contract",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="contract",
            index=models.Index(
                fields=["organisation", "status"], name="contract_org_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contract",
            index=models.Index(fields=["agent"], name="contract_agent_idx"),
        ),
    ]
