# Generated by Django 4.2.24 on 2025-09-17 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='contract',
            new_name='contract_org_status_idx',
            old_name='contracts_c_organis_09059c_idx',
        ),
        migrations.RenameIndex(
            model_name='contract',
            new_name='contract_athlete_idx',
            old_name='contracts_c_athlete_5b086e_idx',
        ),
        migrations.RenameIndex(
            model_name='contract',
            new_name='contract_start_idx',
            old_name='contracts_c_start_d_4c01aa_idx',
        ),
        migrations.AlterUniqueTogether(
            name='contractclause',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='contractversion',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='contractclause',
            constraint=models.UniqueConstraint(fields=('contract', 'template', 'order_index'), name='unique_contract_clause_order'),
        ),
        migrations.AddConstraint(
            model_name='contractversion',
            constraint=models.UniqueConstraint(fields=('contract', 'version_number'), name='unique_contract_version_number'),
        ),
    ]
