# Generated by Django 4.2.24 on 2025-09-21 14:59

from django.db import migrations, models


NEW_CATEGORIES = {
    "obligations": "legal_obligations",
    "finance": "financial",
    "ip": "intellectual_property",
    "ethics": "ethics_morality",
    "confidentiality": "confidentiality",
    "termination": "legal_obligations",
    "administrative": "administrative",
}


def forwards(apps, schema_editor):
    ClauseTemplate = apps.get_model("contracts", "ClauseTemplate")

    for template in ClauseTemplate.objects.all():
        new_value = NEW_CATEGORIES.get(template.category)
        if new_value and new_value != template.category:
            template.category = new_value
            template.save(update_fields=["category"])


def backwards(apps, schema_editor):
    ClauseTemplate = apps.get_model("contracts", "ClauseTemplate")

    reverse_mapping = {
        "legal_obligations": "obligations",
        "financial": "finance",
        "intellectual_property": "ip",
        "ethics_morality": "ethics",
        "confidentiality": "confidentiality",
        "administrative": "administrative",
    }

    for template in ClauseTemplate.objects.all():
        old_value = reverse_mapping.get(template.category, "obligations")
        if old_value != template.category:
            template.category = old_value
            template.save(update_fields=["category"])


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0004_update_contract_workflow_models"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
        migrations.AlterField(
            model_name="clausetemplate",
            name="category",
            field=models.CharField(
                choices=[
                    ("legal_obligations", "Obligatoires (juridiques)"),
                    ("financial", "Financières"),
                    ("athlete_obligations", "Obligations de l’athlète"),
                    ("organisation_obligations", "Obligations de l’organisation"),
                    ("intellectual_property", "Propriété intellectuelle"),
                    ("confidentiality", "Confidentialité"),
                    ("performance", "Performance"),
                    ("ethics_morality", "Éthique et moralité"),
                    ("logistics", "Logistique"),
                    ("administrative", "Administratives"),
                ],
                max_length=32,
            ),
        ),
    ]
