# Generated by Django 4.2.24 on 2025-09-21 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


def seed_initial_versions(apps, schema_editor):
    Contract = apps.get_model("contracts", "Contract")
    ContractVersion = apps.get_model("contracts", "ContractVersion")
    Collaborator = apps.get_model("organisations", "Collaborator")
    AgentProfile = apps.get_model("users", "AgentProfile")
    app_label, model_name = settings.AUTH_USER_MODEL.split(".")
    User = apps.get_model(app_label, model_name)

    for contract in Contract.objects.all():
        if contract.current_version_number:
            continue

        created_by = None

        if contract.initiated_by_id:
            collaborator = (
                Collaborator.objects.select_related("user")
                .filter(id=contract.initiated_by_id)
                .first()
            )
            if collaborator:
                created_by = collaborator.user

        if created_by is None and contract.agent_id:
            agent_profile = (
                AgentProfile.objects.select_related("user")
                .filter(id=contract.agent_id)
                .first()
            )
            if agent_profile:
                created_by = agent_profile.user

        if created_by is None:
            collaborator = (
                Collaborator.objects.select_related("user")
                .filter(organisation_id=contract.organisation_id)
                .first()
            )
            if collaborator:
                created_by = collaborator.user

        if created_by is None:
            created_by = User.objects.filter(is_superuser=True).first()

        if created_by is None:
            continue

        ContractVersion.objects.create(
            contract=contract,
            number=1,
            created_by=created_by,
            notes="Initial version",
        )
        Contract.objects.filter(pk=contract.pk).update(current_version_number=1)


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contracts", "0005_alter_clausetemplate_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="agent_agreed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contract",
            name="current_version_number",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="contract",
            name="owner_agreed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contract",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("negotiation", "Negotiation"),
                    ("agreement", "Agreement"),
                    ("legal_review", "Legal review"),
                    ("signing", "Signing"),
                    ("active", "Active"),
                    ("expired", "Expired"),
                    ("terminated", "Terminated"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ContractVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.PositiveIntegerField()),
                ("notes", models.TextField(blank=True)),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="contracts.contract",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_contract_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_revision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resulting_versions",
                        to="contracts.contractrevision",
                    ),
                ),
            ],
            options={
                "ordering": ("-number",),
                "unique_together": {("contract", "number")},
            },
        ),
        migrations.CreateModel(
            name="ContractSigning",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("envelope_id", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("initiated", "Initiated"),
                            ("completed", "Completed"),
                            ("declined", "Declined"),
                            ("error", "Error"),
                        ],
                        default="initiated",
                        max_length=32,
                    ),
                ),
                ("last_payload", models.JSONField(blank=True, default=dict)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "contract",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signing",
                        to="contracts.contract",
                    ),
                ),
                (
                    "initiated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="initiated_contract_signings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="ContractLegalReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("notes", models.TextField(blank=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("verification_notes", models.TextField(blank=True)),
                (
                    "contract",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="legal_review",
                        to="contracts.contract",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requested_contract_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_contract_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="ContractComment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("body", models.TextField()),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contract_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "clause",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="comments",
                        to="contracts.contractclause",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="contracts.contract",
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="contracts.contractversion",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at",),
            },
        ),
        migrations.RunPython(seed_initial_versions, migrations.RunPython.noop),
    ]
