# Generated by Django 4.2.24 on 2026-01-07 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracts", "0006_contract_agent_agreed_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractversion",
            name="agreement_status",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Snapshot of agreement status (owner_agreed, agent_agreed)",
            ),
        ),
        migrations.AddField(
            model_name="contractversion",
            name="clauses_snapshot",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Complete snapshot of all clauses at this version",
            ),
        ),
    ]
