# Generated by Django 4.2.24 on 2026-01-07 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contracts", "0007_add_version_snapshots"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractAuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("contract_created", "Contract créé"),
                            ("contract_updated", "Contract mis à jour"),
                            ("contract_deleted", "Contract supprimé"),
                            ("owner_agreed", "Organisation a accepté"),
                            (
                                "owner_revoked_agreement",
                                "Organisation a révoqué l'accord",
                            ),
                            ("agent_agreed", "Agent a accepté"),
                            ("agent_revoked_agreement", "Agent a révoqué l'accord"),
                            ("clause_added", "Clause ajoutée"),
                            ("clause_modified", "Clause modifiée"),
                            ("clause_deleted", "Clause supprimée"),
                            ("revision_created", "Révision créée"),
                            ("revision_accepted", "Révision acceptée"),
                            ("revision_rejected", "Révision rejetée"),
                            ("version_created", "Version créée"),
                            ("submitted_for_review", "Soumis pour révision juridique"),
                            ("legal_approved", "Approuvé par le service juridique"),
                            ("legal_rejected", "Rejeté par le service juridique"),
                            ("signature_initiated", "Signature initiée"),
                            ("signature_completed", "Signature complétée"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "action_details",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional context about the action (clause_id, old/new values, etc.)",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who performed the action (null for system actions)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contract_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="contracts.contract",
                    ),
                ),
            ],
            options={
                "ordering": ("-timestamp",),
                "indexes": [
                    models.Index(
                        fields=["contract", "-timestamp"],
                        name="contracts_c_contrac_54271d_idx",
                    ),
                    models.Index(
                        fields=["action", "-timestamp"],
                        name="contracts_c_action_e2f647_idx",
                    ),
                ],
            },
        ),
    ]
