# Generated by Django 4.2.24 on 2026-01-08 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("organisations", "0010_backfill_owner_from_collaborator"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0010_alter_user_country_alter_user_language"),
        ("athletes", "0011_alter_athlete_country_alter_athlete_nationality"),
        ("contracts", "0008_add_contract_audit_log"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractclause",
            name="locked_placeholders",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Liste des clés de placeholders non modifiables (protégés)",
            ),
        ),
        migrations.AddField(
            model_name="contractclause",
            name="placeholder_values",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Valeurs des placeholders {key: value}",
            ),
        ),
        migrations.CreateModel(
            name="RepresentationMandate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document",
                    models.FileField(
                        help_text="Document de mandat (PDF, image, etc.)",
                        upload_to="mandates/%Y/%m/",
                    ),
                ),
                (
                    "verified",
                    models.BooleanField(
                        default=False, help_text="Mandat vérifié par le staff"
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("valid_from", models.DateField(help_text="Date de début de validité")),
                (
                    "valid_until",
                    models.DateField(
                        blank=True,
                        help_text="Date de fin de validité (None = indéfini)",
                        null=True,
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Agent authorized to represent the athlete",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mandates",
                        to="users.agentprofile",
                    ),
                ),
                (
                    "athlete",
                    models.ForeignKey(
                        blank=True,
                        help_text="Athlete being represented",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mandates",
                        to="athletes.athlete",
                    ),
                ),
                (
                    "collaborator",
                    models.ForeignKey(
                        blank=True,
                        help_text="Collaborator authorized to represent the organisation",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mandates",
                        to="organisations.collaborator",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        blank=True,
                        help_text="Organisation being represented",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mandates",
                        to="organisations.organisation",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_mandates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["agent", "verified"],
                        name="contracts_r_agent_i_8aa6bc_idx",
                    ),
                    models.Index(
                        fields=["collaborator", "verified"],
                        name="contracts_r_collabo_fc8392_idx",
                    ),
                    models.Index(
                        fields=["valid_from", "valid_until"],
                        name="contracts_r_valid_f_4c0ea1_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="representationmandate",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("agent__isnull", False),
                        ("athlete__isnull", False),
                        ("collaborator__isnull", True),
                        ("organisation__isnull", True),
                    ),
                    models.Q(
                        ("agent__isnull", True),
                        ("athlete__isnull", True),
                        ("collaborator__isnull", False),
                        ("organisation__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="mandate_xor_agent_or_collaborator",
            ),
        ),
    ]
