# Generated by Django 4.2.24 on 2026-06-22 23:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("athletes", "0012_sport_business_and_entourage"),
        ("contracts", "0009_phase2_placeholders_and_mandates"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="athlete",
            field=models.ForeignKey(
                blank=True,
                help_text="Athlète concerné par ce contrat (permet le calcul automatique de la minorité).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contracts",
                to="athletes.athlete",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="is_athlete_minor",
            field=models.BooleanField(
                default=False,
                help_text="True si l'athlète est mineur au moment de la signature.",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="legal_guardian_agreed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Horodatage de la co-signature du représentant légal (obligatoire si mineur).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="legal_guardian_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="contract",
            name="legal_guardian_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="contract",
            name="requires_escrow_deposit",
            field=models.BooleanField(
                default=False,
                help_text="Dépôt à la Caisse des Dépôts obligatoire pour certains revenus de mineurs (loi du 19 mai 2015 relative au compte bancaire des mineurs).",
            ),
        ),
        migrations.CreateModel(
            name="PerformanceBonus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "trigger_condition",
                    models.TextField(
                        help_text="Condition précise d'activation (ex : 'Top 8 aux Championnats de France')."
                    ),
                ),
                (
                    "bonus_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Valeur de la prime en euros.",
                        max_digits=10,
                    ),
                ),
                ("is_achieved", models.BooleanField(default=False)),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_bonuses",
                        to="contracts.contract",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at",),
            },
        ),
        migrations.CreateModel(
            name="ImageRightsScope",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "territory",
                    models.CharField(
                        help_text="Zone géographique d'exploitation (ex : 'France métropolitaine', 'Monde entier').",
                        max_length=255,
                    ),
                ),
                (
                    "duration_months",
                    models.PositiveIntegerField(
                        help_text="Durée maximale d'exploitation des visuels après la fin du contrat, en mois."
                    ),
                ),
                (
                    "allowed_media",
                    models.TextField(
                        help_text="Supports autorisés listés explicitement (ex : 'Réseaux sociaux, Print, TV, PLV')."
                    ),
                ),
                (
                    "excludes_club_gear",
                    models.BooleanField(
                        default=False,
                        help_text="L'athlète ne peut pas apparaître en tenue de club pour ce sponsor (protection vis-à-vis du règlement fédéral).",
                    ),
                ),
                (
                    "contract",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="image_rights_scope",
                        to="contracts.contract",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="ContractCounterpart",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("cash", "Numéraire"),
                            ("equipment_dotation", "Dotation de matériel"),
                            ("expense_reimbursement", "Remboursement de frais"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Libellé précis de la contrepartie (ex : '3 paires de pointes', 'Frais kilométriques')."
                    ),
                ),
                (
                    "estimated_value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Valeur marchande estimée en euros (pour déclaration fiscale et couverture assurantielle).",
                        max_digits=10,
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="counterparts",
                        to="contracts.contract",
                    ),
                ),
            ],
            options={
                "ordering": ("type", "created_at"),
            },
        ),
    ]
