# Generated by Django 4.2.24 on 2026-06-23 01:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contracts", "0010_legal_compliance_and_sport_business"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RepresentationMandate",
        ),
    ]
