# Generated by Django 4.2.24 on 2026-06-23 01:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracts", "0010_legal_compliance_and_sport_business"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contractauditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("contract_created", "Contract créé"),
                    ("contract_updated", "Contract mis à jour"),
                    ("contract_deleted", "Contract supprimé"),
                    ("owner_agreed", "Organisation a accepté"),
                    ("owner_revoked_agreement", "Organisation a révoqué l'accord"),
                    ("agent_agreed", "Agent a accepté"),
                    ("agent_revoked_agreement", "Agent a révoqué l'accord"),
                    ("clause_added", "Clause ajoutée"),
                    ("clause_modified", "Clause modifiée"),
                    ("clause_deleted", "Clause supprimée"),
                    ("revision_created", "Révision créée"),
                    ("revision_accepted", "Révision acceptée"),
                    ("revision_rejected", "Révision rejetée"),
                    ("version_created", "Version créée"),
                    ("submitted_for_review", "Soumis pour révision juridique"),
                    ("legal_approved", "Approuvé par le service juridique"),
                    ("legal_rejected", "Rejeté par le service juridique"),
                    ("signature_initiated", "Signature initiée"),
                    ("signature_completed", "Signature complétée"),
                    ("platform_fee_generated", "Invoice générée"),
                    ("platform_fee_paid", "Invoice réglée"),
                ],
                max_length=32,
            ),
        ),
    ]
