# Generated by Django 4.2.24 on 2026-06-23 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0011_marketplace_fee_models'),
        ('contracts', '0011_remove_representationmandate'),
    ]

    operations = [
    ]
