"""Adjust follow indexes and constraints for the follows application."""

# Generated by Django 4.2.24 on 2025-09-17 18:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("follows", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="follow",
            new_name="follow_ath_collab_idx",
            old_name="follows_fol_athlete_490c7f_idx",
        ),
        migrations.AlterUniqueTogether(
            name="follow",
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name="follow",
            index=models.Index(fields=["athlete"], name="follow_athlete_idx"),
        ),
        migrations.AddConstraint(
            model_name="follow",
            constraint=models.UniqueConstraint(
                fields=("collaborator", "athlete"),
                name="unique_follow_collaborator_athlete",
            ),
        ),
    ]
