"""Database models for organisations and their collaborators."""

import secrets
import uuid

from django.conf import settings
from django.db import models
from django.utils.text import slugify
from django.utils import timezone
from django.utils.translation import gettext_lazy as _


class BaseModel(models.Model):
    """Abstract base model providing UUID primary key and timestamps."""

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Organisation(BaseModel):
    """A partner organisation that collaborates with platform users."""

    class Type(models.TextChoices):
        BRAND = "BRAND", _("Brand")
        SME = "SME", _("Small or medium enterprise")
        STARTUP = "STARTUP", _("Startup")
        ASSOCIATION = "ASSOCIATION", _("Association")
        INDIVIDUAL = "INDIVIDUAL", _("Individual")
        AGENCY = "AGENCY", _("Agency")
        OTHER = "OTHER", _("Other")

    name = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique=True, blank=True)
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="owned_organisations",
        null=True,
        blank=True,
    )
    type = models.CharField(max_length=20, choices=Type.choices, default=Type.BRAND)
    industry = models.CharField(max_length=255, blank=True)
    logo = models.ImageField(upload_to="organisation_logos/", blank=True, null=True)
    banner_image = models.ImageField(
        upload_to="organisation_banners/", blank=True, null=True
    )
    description = models.TextField(blank=True)

    website_url = models.URLField(blank=True)
    email_contact = models.EmailField(blank=True)
    phone_contact = models.CharField(max_length=50, blank=True)
    address_city = models.CharField(max_length=255, blank=True)
    address_country = models.CharField(max_length=100, blank=True)
    address_postal_code = models.CharField(max_length=20, blank=True)
    social_links = models.JSONField(default=dict, blank=True)

    founded_year = models.PositiveIntegerField(blank=True, null=True)
    employees_count = models.PositiveIntegerField(blank=True, null=True)
    budget_range = models.CharField(max_length=50, blank=True)
    sponsoring_focus = models.JSONField(default=list, blank=True)

    def get_owner_id(self):
        """Return the collaborator identifier for the organisation owner."""
        owner = self.collaborators.filter(role=Collaborator.Role.OWNER).first()
        return owner.id if owner else None

    def save(self, *args, **kwargs):
        """Ensure the slug is populated from the name when missing."""
        if not self.slug:
            base_slug = slugify(self.name) or uuid.uuid4().hex[:8]
            slug = base_slug
            counter = 1
            while Organisation.objects.filter(slug=slug).exclude(pk=self.pk).exists():
                counter += 1
                slug = f"{base_slug}-{counter}"
            self.slug = slug
        super().save(*args, **kwargs)

    def __str__(self):
        return str(self.name)


class Collaborator(BaseModel):
    """Link a user to an organisation with a specific collaboration role."""

    class Role(models.TextChoices):
        OWNER = "OWNER", _("Owner")
        MEMBER = "MEMBER", _("Member")

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="collaborations",
    )
    organisation = models.ForeignKey(
        Organisation,
        on_delete=models.CASCADE,
        related_name="collaborators",
    )
    role = models.CharField(max_length=10, choices=Role.choices)
    job_title = models.CharField(max_length=255)

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=("organisation",),
                condition=models.Q(role="OWNER"),
                name="unique_owner_per_organisation",
            ),
        ]

    def __str__(self):
        return f"{self.user} - {self.organisation.name} ({self.role})"


class OrganisationInvite(BaseModel):
    """Time-bound invitation codes generated by organisation owners."""

    CODE_LENGTH = 8
    DEFAULT_EXPIRY_HOURS = 72

    organisation = models.ForeignKey(
        Organisation,
        on_delete=models.CASCADE,
        related_name="invites",
    )
    created_by = models.ForeignKey(
        Collaborator,
        on_delete=models.CASCADE,
        related_name="created_invites",
    )
    code = models.CharField(max_length=16, unique=True)
    expires_at = models.DateTimeField()
    is_used = models.BooleanField(default=False)
    used_at = models.DateTimeField(blank=True, null=True)
    used_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name="consumed_invites",
    )

    class Meta:
        indexes = [
            models.Index(fields=("organisation", "is_used", "expires_at")),
            models.Index(fields=("code",)),
        ]

    def mark_used(self, user):
        """Flag the invitation as consumed by the provided user."""
        self.is_used = True
        self.used_by = user
        self.used_at = timezone.now()
        self.save(update_fields=["is_used", "used_by", "used_at", "updated_at"])

    @classmethod
    def generate_code(cls):
        """Return a random uppercase invitation code."""
        alphabet = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789"
        return "".join(secrets.choice(alphabet) for _ in range(cls.CODE_LENGTH))
