"""Rename messaging indexes to readable identifiers."""

# Generated by Django 4.2.24 on 2025-09-17 18:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("messaging", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="message",
            new_name="message_thread_created_idx",
            old_name="messaging_m_thread__1731c3_idx",
        ),
        migrations.RenameIndex(
            model_name="message",
            new_name="message_is_read_idx",
            old_name="messaging_m_is_read_8b9e91_idx",
        ),
        migrations.RenameIndex(
            model_name="thread",
            new_name="thread_collaborator_idx",
            old_name="messaging_t_collabo_36f849_idx",
        ),
        migrations.RenameIndex(
            model_name="thread",
            new_name="thread_agent_idx",
            old_name="messaging_t_agent_i_d42213_idx",
        ),
        migrations.RenameIndex(
            model_name="thread",
            new_name="thread_last_message_desc_idx",
            old_name="messaging_t_last_me_cc3bd9_idx",
        ),
        migrations.AlterUniqueTogether(
            name="thread",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="thread",
            constraint=models.UniqueConstraint(
                fields=("collaborator", "agent", "athlete"),
                name="unique_thread_collaborator_agent_athlete",
            ),
        ),
    ]
