# Generated by Django 4.2.24 on 2025-09-17 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='collaborator',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='collaborator',
            constraint=models.UniqueConstraint(fields=('user', 'organisation'), name='unique_collaborator_per_organisation'),
        ),
    ]
