# pylint: skip-file
# Generated by Django 4.2.24 on 2025-09-17 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0002_alter_collaborator_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='collaborator',
            name='unique_collaborator_per_organisation',
        ),
        migrations.AddConstraint(
            model_name='collaborator',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'OWNER')), fields=('organisation',), name='unique_owner_per_organisation'),
        ),
    ]
