# Generated by Django 4.2.24 on 2025-09-17 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0003_remove_collaborator_unique_collaborator_per_organisation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
