# Generated by Django 4.2.24 on 2025-09-27 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisations", "0005_organisation_owner"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="collaborator",
            name="unique_owner_per_organisation",
        ),
        migrations.AddConstraint(
            model_name="collaborator",
            constraint=models.UniqueConstraint(
                condition=models.Q(("role", "OWNER")),
                fields=("organisation", "user"),
                name="unique_owner_per_organisation_user",
            ),
        ),
    ]
