# Generated by Django 4.2.24 on 2025-10-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0006_remove_organisation_budget_max_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='collaborator',
            constraint=models.UniqueConstraint(fields=('user',), name='unique_collaborator_user_global'),
        ),
    ]
