# Generated by Django 4.2.24 on 2025-10-03 13:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organisations", "0007_collaborator_unique_collaborator_user_global"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="collaborator",
            index=models.Index(
                fields=["user", "created_at"], name="collab_user_created_idx"
            ),
        ),
    ]
