# Generated by Django 4.2.24 on 2026-06-23 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organisations", "0010_backfill_owner_from_collaborator"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisationinvite",
            name="target_email",
            field=models.EmailField(
                blank=True,
                help_text="Optional email address of the intended recipient; when provided, an invitation email is sent automatically.",
                max_length=254,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="InvitationAuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATED", "Created"),
                            ("ACCEPTED", "Accepted"),
                            ("REVOKED", "Revoked"),
                            ("EXPIRED", "Expired"),
                        ],
                        max_length=16,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=512)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invitation_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invite",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="organisations.organisationinvite",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["invite", "-created_at"],
                        name="inviteaudit_invite_created_idx",
                    )
                ],
            },
        ),
    ]
