# Generated by Django 4.2.24 on 2025-09-17 17:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_delete_collaborator_delete_organisation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('discipline', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('nationality', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('social_links', models.JSONField(blank=True, default=dict)),
                ('is_self_represented', models.BooleanField(default=False)),
                ('followers_count_cached', models.PositiveIntegerField(default=0)),
                ('engagement_rate_cached', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='athlete_avatars/')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='athletes', to='users.agentprofile')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='athletes', to='athletes.sport')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
