# Generated by Django 4.2.24 on 2025-09-22 02:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("athletes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sport",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name="sport",
            unique_together={("name", "discipline")},
        ),
    ]
