# Generated by Django 4.2.24 on 2025-09-22 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("athletes", "0002_alter_sport_name_alter_sport_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="sport",
            name="emoji",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
