# Generated by Django 4.2.24 on 2025-09-25 21:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("athletes", "0003_sport_emoji"),
        ("users", "0008_agentprofile_is_self_represented"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="athlete",
            name="is_self_represented",
        ),
    ]
