# Generated by Django 4.2.24 on 2025-09-26 01:10

from django.db import migrations


def drop_unused_columns(apps, schema_editor):
    cursor = schema_editor.connection.cursor()

    def drop_column(table, column):
        columns = [row[1] for row in cursor.execute(f"PRAGMA table_info({table})")]
        if column in columns:
            schema_editor.execute(f"ALTER TABLE {table} DROP COLUMN {column};")

    drop_column("athletes_sport", "governing_body")
    drop_column("athletes_sport", "origin_country")
    drop_column("athletes_sport", "origin_year")


def rename_short_description(apps, schema_editor):
    cursor = schema_editor.connection.cursor()
    columns = [row[1] for row in cursor.execute("PRAGMA table_info(athletes_sportdiscipline)")]
    if "short_description" in columns and "description" not in columns:
        schema_editor.execute(
            "ALTER TABLE athletes_sportdiscipline RENAME COLUMN short_description TO description;"
        )


class Migration(migrations.Migration):

    dependencies = [
        ("athletes", "0005_sport_slug_and_disciplines"),
    ]

    operations = [
        migrations.RunPython(drop_unused_columns, migrations.RunPython.noop),
        migrations.RunPython(rename_short_description, migrations.RunPython.noop),
    ]
