# Generated by Django 4.2.24 on 2026-06-22 23:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_add_representative_profile"),
        ("athletes", "0011_alter_athlete_country_alter_athlete_nationality"),
    ]

    operations = [
        migrations.AddField(
            model_name="athlete",
            name="club_name",
            field=models.CharField(
                blank=True,
                help_text="Club actuel de l'athlète (affilié à la fédération).",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="athlete",
            name="federation_name",
            field=models.CharField(
                blank=True,
                help_text="Fédération sportive nationale (ex : Fédération Française de Judo).",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="athlete",
            name="license_number",
            field=models.CharField(
                blank=True,
                help_text="Numéro de licence fédérale (optionnel, utilisé pour la vérification d'identité sportive).",
                max_length=100,
            ),
        ),
        migrations.CreateModel(
            name="SportingAchievement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("date", models.DateField()),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("local", "Local"),
                            ("regional", "Régional"),
                            ("national", "National"),
                            ("international", "International"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "ranking",
                    models.CharField(
                        blank=True,
                        help_text="Classement obtenu (ex : '1er', 'Top 10', 'Demi-finaliste').",
                        max_length=64,
                    ),
                ),
                (
                    "proof_url",
                    models.URLField(
                        blank=True,
                        help_text="Lien vers les résultats officiels de la fédération ou de l'organisateur.",
                    ),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente de vérification"),
                            ("verified", "Vérifié ✓"),
                            ("rejected", "Rejeté"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "athlete",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="achievements",
                        to="athletes.athlete",
                    ),
                ),
            ],
            options={
                "ordering": ("-date",),
            },
        ),
        migrations.CreateModel(
            name="SponsorshipAsset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            (
                                "physical_gear",
                                "Équipement physique (logo sur tenue / matériel)",
                            ),
                            (
                                "digital_shoutout",
                                "Publication digitale (réseaux / newsletter)",
                            ),
                            (
                                "event_presence",
                                "Présence physique (inauguration, activation)",
                            ),
                            (
                                "image_rights",
                                "Droit à l'image (campagne photo / vidéo)",
                            ),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Libellé commercial de l'espace (ex : 'Logo épaule gauche sur le kimono').",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Détails : dimensions, conditions d'utilisation, fréquence d'exposition."
                    ),
                ),
                (
                    "estimated_value_min",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Borne basse de la fourchette tarifaire en euros.",
                        max_digits=10,
                    ),
                ),
                (
                    "estimated_value_max",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Borne haute de la fourchette tarifaire en euros.",
                        max_digits=10,
                    ),
                ),
                ("is_available", models.BooleanField(default=True)),
                (
                    "athlete",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sponsorship_assets",
                        to="athletes.athlete",
                    ),
                ),
            ],
            options={
                "ordering": ("asset_type", "name"),
            },
        ),
        migrations.CreateModel(
            name="RepresentationMandate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("parent_guardian", "Parent / Legal Guardian"),
                            ("coach", "Coach"),
                            ("club_official", "Club Official"),
                            ("licensed_agent", "Licensed Sports Agent"),
                            ("manager", "Manager"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "can_manage_messaging",
                    models.BooleanField(
                        default=False,
                        help_text="May communicate with sponsors via the messaging module.",
                    ),
                ),
                (
                    "can_negotiate_contracts",
                    models.BooleanField(
                        default=False,
                        help_text="May open, edit, and counter-propose contract clauses.",
                    ),
                ),
                (
                    "can_sign_legally",
                    models.BooleanField(
                        default=False,
                        help_text="May sign contracts with legal effect.  Blocked automatically for coaches and club officials when the athlete is under 18.",
                    ),
                ),
                (
                    "commission_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Agreed commission rate in percent (0.00–20.00).  Must be 0 for non-agent roles.",
                        max_digits=5,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive mandates are ignored by permission checks.  Deactivate rather than delete to preserve the audit trail.",
                    ),
                ),
                (
                    "athlete",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entourage_mandates",
                        to="athletes.athlete",
                    ),
                ),
                (
                    "representative",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mandates",
                        to="users.representativeprofile",
                    ),
                ),
            ],
            options={
                "ordering": ("role", "created_at"),
            },
        ),
        migrations.AddField(
            model_name="athlete",
            name="entourage",
            field=models.ManyToManyField(
                blank=True,
                related_name="represented_athletes",
                through="athletes.RepresentationMandate",
                to="users.representativeprofile",
            ),
        ),
        migrations.CreateModel(
            name="UpcomingEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("event_name", models.CharField(max_length=255)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "location",
                    models.CharField(
                        help_text="Ville, région ou pays (ex : 'Bordeaux, Nouvelle-Aquitaine').",
                        max_length=255,
                    ),
                ),
                (
                    "estimated_physical_audience",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Nombre estimé de spectateurs présents physiquement.",
                    ),
                ),
                (
                    "target_demographic",
                    models.CharField(
                        blank=True,
                        help_text="Profil du public cible (ex : 'Familles', 'B2B', 'Jeunes 15-25 ans').",
                        max_length=255,
                    ),
                ),
                (
                    "is_broadcasted",
                    models.BooleanField(
                        default=False,
                        help_text="True si l'événement fait l'objet d'une captation vidéo ou d'un stream.",
                    ),
                ),
                (
                    "athlete",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="upcoming_events",
                        to="athletes.athlete",
                    ),
                ),
            ],
            options={
                "ordering": ("start_date",),
                "indexes": [
                    models.Index(
                        fields=["athlete", "start_date"],
                        name="event_athlete_start_date_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="upcomingevent",
            constraint=models.CheckConstraint(
                check=models.Q(("end_date__gte", models.F("start_date"))),
                name="event_end_date_gte_start_date",
            ),
        ),
        migrations.AddIndex(
            model_name="sportingachievement",
            index=models.Index(
                fields=["athlete", "verification_status"],
                name="achievement_athlete_status_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="sportingachievement",
            index=models.Index(
                fields=["athlete", "level"], name="achievement_athlete_level_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sponsorshipasset",
            index=models.Index(
                fields=["athlete", "is_available"], name="asset_athlete_available_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="sponsorshipasset",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("estimated_value_max__gte", models.F("estimated_value_min"))
                ),
                name="asset_value_max_gte_min",
            ),
        ),
        migrations.AddIndex(
            model_name="representationmandate",
            index=models.Index(
                fields=["athlete", "is_active"], name="mandate_athlete_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="representationmandate",
            index=models.Index(
                fields=["representative", "is_active"], name="mandate_rep_active_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="representationmandate",
            unique_together={("athlete", "representative")},
        ),
    ]
