# Generated by Django 4.2.24 on 2026-06-23 01:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("athletes", "0012_sport_business_and_entourage"),
    ]

    operations = [
        migrations.AddField(
            model_name="representationmandate",
            name="proof_document",
            field=models.FileField(
                blank=True,
                help_text="Document de procuration (PDF). Obligatoire pour les agents sportifs licenciés ; optionnel pour les autres rôles (parents, coachs...).",
                null=True,
                upload_to="mandates/%Y/%m/",
            ),
        ),
        migrations.AddField(
            model_name="representationmandate",
            name="valid_from",
            field=models.DateField(
                blank=True,
                help_text="Date de début de validité (défaut : date de création).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="representationmandate",
            name="valid_until",
            field=models.DateField(
                blank=True,
                help_text="Date de fin de validité (None = indéfini).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="representationmandate",
            name="verified",
            field=models.BooleanField(
                default=False, help_text="Mandat vérifié par le staff de la plateforme."
            ),
        ),
        migrations.AddField(
            model_name="representationmandate",
            name="verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="representationmandate",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_athlete_mandates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
