"""Initial schema for notifications app."""

# Generated by Django 4.2.24 on 2025-09-17 18:02


import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'type',
                    models.CharField(
                        choices=[
                            ('NEW_MESSAGE', 'New Message'),
                            ('CONTRACT_STATUS', 'Contract Status'),
                            ('NEW_FOLLOW', 'New Follow'),
                            ('STAT_UPDATE', 'Stat Update'),
                            ('PAYMENT', 'Payment'),
                        ],
                        max_length=32,
                    ),
                ),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='notifications',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [
                    models.Index(
                        fields=['user', 'is_read', '-created_at'],
                        name='notificatio_user_id_f2ad08_idx',
                    ),
                ],
            },
        ),
    ]
